version: 2
jobs:
  build:
#    branches:
#      only:
#        - master
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ls -lart
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
      - run: |
          gradle build
          ls -lart
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t bitbyte01/cargaraage:$CIRCLE_BUILD_NUM .
      - run:
          name: Docker Hub Login
          command: echo $DOCKER_PWD | docker login -u $DOCKER_UNAME --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push bitbyte01/cargaraage:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              ignore: readme
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: readme