version: 2
jobs:
  build:
#    branches:
#      only:
#        - master
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ls -lart
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
      - run: |
          gradle build
          ls -lart
          mkdir /tmp/build
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - build/*
      - run: ls -lart /tmp

  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - attach_workspace:
          path: /tmp/build
      - run: ls -lart

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              ignore: readme
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: readme